version: '3.4'

services:
  testapi:
    image: ${DOCKER_REGISTRY-}testapi
    build:
      context: .
      dockerfile: TestApi/Dockerfile
    ports:
      - "6086:80"

  test.localstack:
    container_name: test.localstack
    image: localstack/localstack
    ports:
      - "4566-4576:4566-4576"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=sns,sqs,s3, dynamodb, kinesis
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=1
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  test.aws.builder:
    image: mesosphere/aws-cli
    container_name: test.aws.builder
    volumes:
      - ./dev_env:/project/dev_env
    environment:
      - AWS_ACCESS_KEY_ID=AKIAEXAMPLE123
      - AWS_SECRET_ACCESS_KEY=AWSSECRETACCESSEY123
      - AWS_DEFAULT_REGION=eu-west-1
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 20
        # Executing SNS
        aws sns create-topic --name test_sm_topic --endpoint-url=http://test.localstack:4566 
        # Executing SQS
        aws sqs create-queue --endpoint-url=http://test.localstack:4566 --queue-name test_sm_queue;
        # Subscribing to SNS to SQS
        subscription_arn=$$(aws --endpoint-url=http://test.localstack:4566 sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:test_sm_topic --protocol sqs --notification-endpoint http://test.localstack:4566/queue/test_sm_queue --output text)
        echo \"Subscription ARN: $$subscription_arn\"
        #Enable RawMessageDelivery
        aws sns set-subscription-attributes --endpoint-url=http://test.localstack:4566 --subscription-arn \"$$subscription_arn\" --attribute-name RawMessageDelivery --attribute-value 'True'

        # create S3 bucket
        aws --endpoint-url=http://test.localstack:4566 s3 mb s3://source-bucket

        aws --endpoint-url=http://test.localstack:4566 dynamodb create-table --table-name MusicCollection  \
            --attribute-definitions AttributeName=Artist,AttributeType=S AttributeName=SongTitle,AttributeType=S \
            --key-schema AttributeName=Artist,KeyType=HASH AttributeName=SongTitle,KeyType=RANGE \
            --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1  
      
        aws --endpoint-url=http://test.localstack:4566 dynamodb scan --table-name MusicCollection

        aws --endpoint-url=http://test.localstack:4566 s3 ls

      "
    depends_on:
      - test.localstack

volumes:
  localstack_dir:
