version: '3.4'

services:
  testapi:
    image: ${DOCKER_REGISTRY-}testapi
    build:
      context: .
      dockerfile: TestApi/Dockerfile

  test.localstack:
    container_name: test.localstack
    image: localstack/localstack
    ports:
      - "4566-4576:4566-4576"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=sns,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - DATA_DIR=tmp/localstack/data
      - START_WEB=1
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_dir:/tmp/localstack

  sqs.sns.builder:
    image: mesosphere/aws-cli
    container_name: sqs.sns.builder
    volumes:
      - ./dev_env:/project/dev_env
    environment:
      - AWS_ACCESS_KEY_ID=AKIAEXAMPLE123
      - AWS_SECRET_ACCESS_KEY=AWSSECRETACCESSEY123
      - AWS_DEFAULT_REGION=eu-west-1
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 20
        # Executing SNS
        aws sns create-topic --name test_sm_topic --endpoint-url=http://test.localstack:4566 
        # Executing SQS
        aws sqs create-queue --endpoint-url=http://test.localstack:4566 --queue-name test_sm_queue;
        # Subscribing to SNS to SQS
        subscription_arn=$$(aws --endpoint-url=http://test.localstack:4566 sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:test_sm_topic --protocol sqs --notification-endpoint http://test.localstack:4566/queue/test_sm_queue --output text)
        echo \"Subscription ARN: $$subscription_arn\"
        #Enable RawMessageDelivery
        aws sns set-subscription-attributes --endpoint-url=http://test.localstack:4566 --subscription-arn \"$$subscription_arn\" --attribute-name RawMessageDelivery --attribute-value 'True'
      "
    depends_on:
      - test.localstack

volumes:
  localstack_dir:
